version: "3"

services:
  bot:
    build: ./
    container_name: any-url-bot
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: 4
    environment:
      WEBHOOK_URL: https://${WEBHOOK_HOST}/
    env_file:
      - ".env"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anyUrlBot.rule=Host(`${WEBHOOK_HOST}`) && Headers(`X-Telegram-Bot-Api-Secret-Token`, `${WEBHOOK_SECRET}`)"
      - "traefik.http.routers.anyUrlBot.entryPoints=web"
      - "traefik.http.routers.anyUrlBot.middlewares=TGIPWhitelist@file"
      - "traefik.http.routers.anyUrlBot.tls=true"
      - "traefik.http.routers.anyUrlBot.tls.certresolver=cloudflare"
      - "traefik.http.services.anyUrlBot.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
